### ISSUE TITLE
Tokocrypto: Incorrect filled order timestamp

### ISSUE THREAD

**Issue by rxlxrxsx** [Tokocrypto/hummingbot#12]
**Describe the bug**
Executing trades thru the bot using Tokocrypto results to an incorrect filled order timestamp. Upon further checking I noticed that on all instances the trades are only recorded whenever the orders are about to get cancelled.

Example:

Actual timestamp of this order on the exchange `2022-11-21 09:26:25`

<img width="1096" alt="Screen Shot 2022-11-21 at 9 26 48 AM" src="https://user-images.githubusercontent.com/64377055/202941506-bf2de7bc-8f09-4603-99d1-616616e459ba.png">

Filled order timestamp on the bot `2022-11-21 09:26:47`
<img width="1423" alt="Screen Shot 2022-11-21 at 9 27 02 AM" src="https://user-images.githubusercontent.com/64377055/202942647-c62a37c4-a5a6-489b-b6bf-1f0a4d8a2914.png">

Same result when executing `history --verbose` command
<img width="681" alt="Screen Shot 2022-11-21 at 9 27 13 AM" src="https://user-images.githubusercontent.com/64377055/202942709-27cb5e77-736a-4045-a6b2-0a7fbe380068.png">

**Steps To Reproduce**
1. Create and run a pure market making bot using Tokocrypto
2. Set tight spreads to execute trades faster
3. Monitor the trade history on the exchange
4. Check the bot and notice that the filled trade doesn't appear yet and will only be recorded when the order is about to be cancelled

**Release version**
Version: dev-1.10.0

**Attachments**
Logs, config and data files: 
[toko_filled.zip](https://github.com/Tokocrypto/hummingbot/files/10051746/toko_filled.zip)

**Comment by toriqahmads** [comment]
Hi @rxlxrxsx ,

Thank you for reporting the bug.

After tracing the bug, the order filled timestamp is not correct because, in the order dashboard is parsed from createTime field response, and in the bot is parsed from the timestamp field response. I will change it to createTime field response if it needed.

And for the order filled only updated when order being canceled, it because the heartbeat of the user data stream websocket is 30s, and the order refresh time config is 10s. Also I modify the order cancelation function to do update order and balance after the request cancelation from server (tokocrypto) failed because some order maybe already filled but not updated yet by the bot.

This is the heatbeat:
![image](https://user-images.githubusercontent.com/33996579/202966868-380f5da4-2391-4359-be88-4d283b1c1b4f.png)

This is the validation for order cancelation:
![image](https://user-images.githubusercontent.com/33996579/202967222-ea4c8647-f5cf-4a7b-b9b2-3df13b482712.png)


Thank you

**Comment by toriqahmads** [comment]
Just fixed in commit: https://github.com/Tokocrypto/hummingbot/commit/9e2a32ba53e92b1c6539b05eb7c938d92a97d2f4

Kindly check and retest again

Thank you

**Comment by gerald-hb** [comment]
This looks fixed on the latest commit, however I just want to clarify what this message in the logpane means.
![image](https://user-images.githubusercontent.com/84826167/203058604-b280c5f0-9b1f-4dc9-ab85-85d9a7fd9680.png)

**Comment by toriqahmads** [comment]
Hi @gerald-hb 


Since this connector is refers to binance connector, the exchange_base have _update_order_fills_from_trades function that will triggered every 10s in minimum. This function is to recheck the trade record. If it not tracked and stored in the db, it will recreate the trade record to db.

![image](https://user-images.githubusercontent.com/33996579/203214428-25c647d5-307b-4634-ab78-9f35a718be45.png)

**Comment by gerald-hb** [comment]
Thank you for clarifying @toriqahmads. We will close this bug report
