### ISSUE TITLE
Tokocrypto: Number of filled trades differ on the client and on the exchange

### ISSUE THREAD

**Issue by gerald-hb** [Tokocrypto/hummingbot#13]
**Describe the bug**
There is a discrepancy on recorded filled orders on the exchange and on the client/tradecsv. On my most recent test, I got 8 trades recorded in the exchange.
![image](https://user-images.githubusercontent.com/84826167/203056592-c84025c2-1b4c-4ca8-85f9-fd7992e8955e.png)
But on the client, it shows 15
![image](https://user-images.githubusercontent.com/84826167/203056729-e76758a4-3e5e-48b3-a6a9-7d6a0d19a112.png)

**Steps To Reproduce**
1.Create a PMM strategy using tokocrypto
2.set a tight spread to get orders filled easily. 
3.Run the bot for 10-20 minutes. Compare result on the history/history --verbose vs the recorded filled trades on the exchange

**Release version**
Version: dev-1.10.0 

**Attachments**
[tokotrades.zip](https://github.com/Tokocrypto/hummingbot/files/10056570/tokotrades.zip)

**Comment by RC-13** [comment]
Just to add, it looks like the filled data is stored twice in the client which caused the trade count mismatched
![image](https://user-images.githubusercontent.com/57189990/203195274-dca1e580-0628-49c6-90df-e0b01b5af6b5.png)
![image](https://user-images.githubusercontent.com/57189990/203195704-3a8fb13b-0493-4675-b543-8f3c698ea757.png)
In the log file, only two orders got filled: order IDs `xTKOTCBTOUT5edfde8ff88af77aad1ff` and `xTKOTCSTOUT5ee033213791177aad1ff`

[tokocrypto-duplicate-record.zip](https://github.com/Tokocrypto/hummingbot/files/10062320/tokocrypto-duplicate-record.zip)

**Comment by toriqahmads** [comment]
Hi @gerald-hb 

Thank you for reporting the bug

This bug happen because the filled order recorded twice in DB as @RC-13 mentioned above. This caused because the tradeId from user trade stream websocket is different with tradeId from fetching via this endpoint API: https://www.tokocrypto.com/apidocs/#account-trade-list-signed , so the trade order record will not detected in DB.
I just fixed this by modifying the trade update process in user trade stream function to be refetch first to get the actual tradeId before trigger the trade update function and bot store it in DB.

Note: trade record in bot is based on every trade record fetched from API, this mean partially filled will also saved as trade records

Commit: https://github.com/Tokocrypto/hummingbot/commit/0fb8cf26ede8c923cf90330b41208d6b556b8710

Thank you

**Comment by gerald-hb** [comment]
Thank you @toriqahmads. Confirmed fixed on https://github.com/Tokocrypto/hummingbot/commit/0fb8cf26ede8c923cf90330b41208d6b556b8710
